wiremock:
  server:
    port: 9090
    stubs: classpath:/mappings
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
#spring:
#  cloud:
#    gateway:
#      httpclient:
#        ssl:
#          use-insecure-trust-manager: true
#spring:
#  cloud: 
#    gateway: 
#      routes:
#      - id: dave
#        uri: http://localhost:9090/api/1/customers/1234
#        predicates:
#        - Path=/customers/          
#      - id: baeldung_route
#        uri: http://baeldung.com
#        predicates:
#        - Path=/baeldung/

